import 'package:riverpod_annotation/riverpod_annotation.dart';

import '../../auth/application/auth_state.dart';
import '../../auth/application/device_id_manager.dart';
import '../data/models/room_connection_params.dart';

part 'connection_params_builder.g.dart';

/// Builds dynamic LiveKit room connection parameters based on auth state
/// NOTE: Room names are NOW generated by the server, not client-side
/// This builder only provides participantName and optional interviewType
class ConnectionParamsBuilder {
  final DeviceIdManager _deviceIdManager;

  ConnectionParamsBuilder(this._deviceIdManager);

  /// Build connection parameters based on current authentication state
  /// Server will generate the room name based on user type and authentication
  Future<RoomConnectionParams> buildParams({
    required AuthState authState,
    String? interviewType,
  }) async {
    return await authState.when(
      authenticated: (user) async {
        // For authenticated users: use user's name, or email, or fallback to "User"
        return RoomConnectionParams(
          participantName: user.name.isNotEmpty
              ? user.name
              : (user.email ?? 'User'),
          interviewType: interviewType,
        );
      },
      // For all other states (unauthenticated, initial, loading, error)
      // treat as anonymous/guest user
      initial: () => _buildAnonymousParams(interviewType),
      loading: () => _buildAnonymousParams(interviewType),
      unauthenticated: () => _buildAnonymousParams(interviewType),
      error: (_) => _buildAnonymousParams(interviewType),
    );
  }

  /// Build parameters for anonymous/guest users
  /// Uses persistent device ID for guest identifier
  /// Server will generate the actual room name
  Future<RoomConnectionParams> _buildAnonymousParams(
    String? interviewType,
  ) async {
    final deviceId = await _deviceIdManager.getOrCreateDeviceId();
    final shortId = deviceId.substring(0, 8);

    return RoomConnectionParams(
      participantName: 'Guest-$shortId',
      interviewType: interviewType,
    );
  }
}

@riverpod
ConnectionParamsBuilder connectionParamsBuilder(Ref ref) {
  final deviceIdManager = ref.read(deviceIdManagerProvider);
  return ConnectionParamsBuilder(deviceIdManager);
}
